# Generated by Django 5.0.3 on 2024-03-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSDS393PROJECT', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attendees', models.ManyToManyField(to='CSDS393PROJECT.userprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
