# Generated by Django 5.0.3 on 2024-03-28 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSDS393PROJECT', '0004_alter_userprofile_profilepicture_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_attending',
            new_name='are_attending',
        ),
    ]
