# Generated by Django 5.0.3 on 2024-03-28 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSDS393PROJECT', '0005_rename_is_attending_attendance_are_attending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='are_attending',
            new_name='is_attending',
        ),
    ]
