# Generated by Django 5.0.3 on 2024-03-28 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSDS393PROJECT', '0006_rename_are_attending_attendance_is_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(db_column='creator', on_delete=django.db.models.deletion.CASCADE, to='CSDS393PROJECT.userprofile', to_field='username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
