# Generated by Django 5.0.4 on 2024-04-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSDS393PROJECT', '0009_remove_comment_parent_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Our Group', max_length=200)),
                ('creator', models.ForeignKey(db_column='creator', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='CSDS393PROJECT.userprofile', to_field='profileName')),
                ('members', models.ManyToManyField(to='CSDS393PROJECT.userprofile')),
            ],
        ),
    ]
