# Generated by Django 5.0.4 on 2024-04-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSDS393PROJECT', '0010_event_is_private_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
